### ISSUE TITLE
would you support Screenshots API ?

### ISSUE THREAD

**Issue by island205** [scottgonzalez/node-browserstack#25]
`node-browserstack` has `takeScreenshot` API now, but there is another API service [Screenshots API](http://www.browserstack.com/screenshots/api), would `node-browserstack` support it ?

**Comment by kartsims** [comment]
I could be interested in developing the screenshot API because it's a shame your lib doesn't do it as it the most active and has the simplest name on NPM...

Apart from the lib's API do you see any difficulty I should be aware of before implementing it ?

From what I see it is just all about calling different endpoints, the screenshots API is much simpler and resides under www.browserstack.com instead of api.browserstak.com ([docs here](https://www.browserstack.com/screenshots/api))

**Comment by scottgonzalez** [comment]
Calling the new API should be simple. It's a matter of defining the API and making sure there's no confusion about the two types of screenshots. Perhaps just overloading the existing method to accept a hash of settings instead of an ID would work.

**Comment by kartsims** [comment]
OK how about creating a specific client for the screenshots API using a method like `BrowserStack.createScreenshotClient` instead of `BrowserStack.createClient` ?

Usage examples :
```
var BrowserStack = require( "browserstack" );
var screenshotClient = BrowserStack.createScreenshotClient({
    username: "foo",
    password: "p455w0rd!!1"
});

screenshotClient.getBrowsers(function( error, browsers ) {
    console.log( "The following browsers are available for testing" );
    console.log( browsers );
});

screenshotClient.getScreenshot(options, function( error, job ) {
    console.log( "Created a new job" );
    console.log( job );
});

screenshotClient.getJob(job_id, function( error, job ) {
    console.log( "This job status" );
    console.log( job );
});
```

Otherwise we could implement with the same client and different methods but I am afraid users would get confused. What do you think ?

**Comment by scottgonzalez** [comment]
That sounds good and has nice symmetry with the existing API.

This is also extremely close to the API for [node-browserstack](https://www.npmjs.com/package/node-browserstack) so maybe this will help with https://github.com/bramstein/node-browserstack/issues/3 as well :star2:

**Comment by kartsims** [comment]
Cool

Yes I have taken a look at the available options, including this other npm
package and you made the difference by supporting the v4 API, the package
name (plain and simple "browserstack") and because of the nice readme... It
is not much but it would certainly be nice to have both.

Also I should mention that I prefer @bramstein
<https://github.com/bramstein> 's approach regarding the constructor
parameters (two parameters instead of an object). But that is not a big
deal anyway.

I will work on it soon and send a PR

2015-11-06 21:38 GMT+01:00 Scott González <notifications@github.com>:

**Comment by jzaefferer** [comment]
This looks like it can be closed.

**Comment by scottgonzalez** [comment]
Yup. Forgot to add the reference when I landed the PR. Thanks for reminding me.
