### ISSUE TITLE
v1.1.1 gives EACCESS?

### ISSUE THREAD

**Issue by phun-ky** [scottgonzalez/node-browserstack#31]
I had to roll back to `~1.0` for browserstack to make the `karma-browserstack-launcher` to work

ref: 

https://github.com/karma-runner/karma-browserstack-launcher/issues/23

**Comment by scottgonzalez** [comment]
I highly doubt the bug is in this module. Here's the full diff of v1.0.0 to v1.1.1: https://github.com/scottgonzalez/node-browserstack/compare/v1.0.0...v1.1.1

I'm going to close this since the repro case requires using other modules and the error that is thrown doesn't is from the tunnel, and not from this module. If it turns out that something in this module does need to change, please provide a test case that shows the problem directly with this module.
